version: 2.1
orbs:
  node: circleci/node@4.0

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: main

jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Unit Tests
          command: npm test
      - run:
          name: Build
          command: npm run build
      - run:
          name: Create Deployment Directory
          command: mkdir DEPLOY-$(date +"%Y-%m-%d")
      - persist_to_workspace:
          root: .
          paths:
            - DEPLOY-*
