version: 2.1

jobs:
  build:
    docker:
      - image: python:3.2

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

      # Run tests
      - run:
          name: Run Tests
          command: pytest

      # Build step - you can modify this as needed
      - run:
          name: Build
          command: |
            # Add your build commands here
            echo "Building the project..."

  deploy:
    docker:
      - image: python:3.8

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

      # Deployment step
      - run:
          name: Deployment
          command: |
            # Create deployment directory with current date
            mkdir DEPLOY-$(date +"%Y-%m-%d")
            
            # Copy build artifacts or other deployment tasks
            # For example:
            cp -r dist/* DEPLOY-$(date +"%Y-%m-%d")

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
