version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  test:
    executor: python-executor
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

      - run:
          name: Run Tests
          command: pytest

  build:
    executor: python-executor
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

      - run:
          name: Build Application
          command: python build_script.py

  deploy:
    executor: python-executor
    steps:
      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Deploy to Server
          command: ./deploy_script.sh
          environment:
            SERVER_HOST: your_server_host
            SSH_KEY: $SSH_KEY

workflows:
  version: 2
  test_build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
