version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7  # Replace with your desired base image
    working_directory: ~/devops
    steps:
      # 1. Checkout your code from the repository
      - checkout
      # 2. Build and test your Dockerized application
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: |
            docker build -t myapp .
      - run:
          name: Run Tests in Docker
          command: |
            docker run myapp pytest -v
      # Additional steps as needed, such as pushing the image to a registry

workflows:
  version: 2
  build-test:
    jobs:
      - build
