version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.8

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - run:
         name: upgrade pip
         command: |
           pip install --upgrade pip
      - run:
          name: Directory
          command: |
            working_directory: ~/devops      


      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            python -m pytest
      - run:
          name: Run Linting
          command: |
            pip install flake8
            flake8

workflows:
  version: 2
  build-test:
    jobs:
      - build


